# Generated by Django 5.2.17 on 2026-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("terms", "Contrato"), ("privacy", "Privacidad")], max_length=10
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
